

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyOTEyYWUwOTIwOWE5YjY2ZGRkMmEwYiIsInVzZXJuYW1lIjoiZWRlazk1IiwiZW1haWwiOiJlcmRhbGtpbmlra0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRTWG1EZW5jdFV6UGpWSUM1Y0IvdWZlMXdoUHdwRXcuS28vbWlSWTZXeHI3OWM0aHltOFBzSyIsIm9uVHlwZSI6IkNvbXBhbnkiLCJhY2NfdHlwZSI6IjYyOTEyYWUwOTIwOWE5YjY2ZGRkMmEwOSIsIl9fdiI6MH0sImlhdCI6MTY1NDUyMjA0OH0.XoCFiWXRt9Mg20VdDbRLRNITLAVlNAD1sNSlFnSbBrI"
}


###



POST http://localhost:4000/login
Content-Type:application/json

{
    "email":"erdalkinik@hotmail.com",
    "password":"123"
}

###

// // order creation

POST http://localhost:5000/orders/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyYTBjMTMxZWNhNGM4NDBhZjY5ZjM3YSIsInVzZXJuYW1lIjoiZWRlazMxIiwiZW1haWwiOiJlcmRhbGtpbmlrQGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkenpEbnZENU8wRmRHSGVhUWZKeDd6LmRFZkVxVFB4eDQ0YVg2YTIwMGdvZWN0bE40aGE0MW0iLCJvblR5cGUiOiJDdXN0b21lciIsImFjY190eXBlIjoiNjJhMGMxMzFlY2E0Yzg0MGFmNjlmMzc4IiwiX192IjowfSwiaWF0IjoxNjU0NzIyODYwLCJleHAiOjE2NTQ3MjQ2NjB9.W1le3EHuUWPXG6AHXp0eFz-wS_upPZDdMWFQhAaSLKg

{
    "to_country":"PL",
    "to_city":"Rz",
    "to_street":"ul Cicha-2"
}




###

// cart Item creation

POST http://localhost:5000/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyYTBjMTMxZWNhNGM4NDBhZjY5ZjM3YSIsInVzZXJuYW1lIjoiZWRlazMxIiwiZW1haWwiOiJlcmRhbGtpbmlrQGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkenpEbnZENU8wRmRHSGVhUWZKeDd6LmRFZkVxVFB4eDQ0YVg2YTIwMGdvZWN0bE40aGE0MW0iLCJvblR5cGUiOiJDdXN0b21lciIsImFjY190eXBlIjoiNjJhMGMxMzFlY2E0Yzg0MGFmNjlmMzc4IiwiX192IjowfSwiaWF0IjoxNjU0NzIyODYwLCJleHAiOjE2NTQ3MjQ2NjB9.W1le3EHuUWPXG6AHXp0eFz-wS_upPZDdMWFQhAaSLKg

{
    "product_id":"62a0c1db260016be07cdfcf8",
    "quantity":2
}


###


GET http://localhost:5000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyOWZjMzg0YTg5NjRlYzZjYjJmNmZlNSIsInVzZXJuYW1lIjoiZWRlazMxIiwiZW1haWwiOiJlcmRhbGtpbmlrQGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkWXNoWEdOTXM3QTVoNzdnVzl3bUdtdXpmYTU1Q3MwVEs1OXN3aW43UE9wVnFLSThuZVEzQ2EiLCJvblR5cGUiOiJDdXN0b21lciIsImFjY190eXBlIjoiNjI5ZmMzODRhODk2NGVjNmNiMmY2ZmUzIiwiX192IjowfSwiaWF0IjoxNjU0Njg0MTA2LCJleHAiOjE2NTQ2ODU5MDZ9.fOY4E5m-wd6jlEMyK9MfkBHJtbR46pGApI-lDpV2rFE

###


GET http://localhost:5000/adverts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyOWY2OGViMzVmMzViMjY4MWM1Mzc1MiIsInVzZXJuYW1lIjoiZWRlazMxIiwiZW1haWwiOiJlcmRhbGtpbmlrQGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkWFpxb0E2dG82OXJpblIubFJENWNTLml4MmYyVm1lMWNndU9pcW1NYUFoeldHZ0U3OWtGUzIiLCJvblR5cGUiOiJDdXN0b21lciIsImFjY190eXBlIjoiNjI5ZjY4ZWIzNWYzNWIyNjgxYzUzNzUwIiwiX192IjowfSwiaWF0IjoxNjU0NjI5MTIwLCJleHAiOjE2NTQ2MzA5MjB9.Rkhx6jwOSPLI8tB_kTVW32JmZt6aV7_C00CxsTcl598


###


POST http://localhost:4000/login
Content-Type:application/json

{
    "email":"erdalkinikk@gmail.com",
    "password":"123"
}

###

//product creation 
POST http://localhost:5000/products/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyYTBjMWJkN2IzZTUxOWM3Nzc3MWUyYSIsInVzZXJuYW1lIjoiZWRlazk1IiwiZW1haWwiOiJlcmRhbGtpbmlra0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQyY1dOSW5YalZydmlxL2JrNDRhalRlbzEuOXJzUkFTcDVTRVFUOWhxZGtqWUh6L1MuSldIVyIsIm9uVHlwZSI6IkNvbXBhbnkiLCJhY2NfdHlwZSI6IjYyYTBjMWJkN2IzZTUxOWM3Nzc3MWUyOCIsIl9fdiI6MH0sImlhdCI6MTY1NDcwMjU0OSwiZXhwIjoxNjU0NzA0MzQ5fQ.i2ZOJMRA65Gp6s2JmolfWQONWgfhLu_16q76b7zzejg

{
    "name":"Dummy Product",
    "description":"Dummy Description",
    "status":"New",
    "price":1000,
    "storage":12
}

###

GET http://localhost:5000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyYTBjMTMxZWNhNGM4NDBhZjY5ZjM3YSIsInVzZXJuYW1lIjoiZWRlazMxIiwiZW1haWwiOiJlcmRhbGtpbmlrQGhvdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkenpEbnZENU8wRmRHSGVhUWZKeDd6LmRFZkVxVFB4eDQ0YVg2YTIwMGdvZWN0bE40aGE0MW0iLCJvblR5cGUiOiJDdXN0b21lciIsImFjY190eXBlIjoiNjJhMGMxMzFlY2E0Yzg0MGFmNjlmMzc4IiwiX192IjowfSwiaWF0IjoxNjU0Nzk0ODEwLCJleHAiOjE2NTQ3OTY2MTB9.rmTqhIzmPvcDM8obb5EptJy7dvuuym5PSNe29L0kkZA


###

GET http://localhost:5000/orders/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyYTBjMWJkN2IzZTUxOWM3Nzc3MWUyYSIsInVzZXJuYW1lIjoiZWRlazk1IiwiZW1haWwiOiJlcmRhbGtpbmlra0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQyY1dOSW5YalZydmlxL2JrNDRhalRlbzEuOXJzUkFTcDVTRVFUOWhxZGtqWUh6L1MuSldIVyIsIm9uVHlwZSI6IkNvbXBhbnkiLCJhY2NfdHlwZSI6IjYyYTBjMWJkN2IzZTUxOWM3Nzc3MWUyOCIsIl9fdiI6MH0sImlhdCI6MTY1NDcyNTExNSwiZXhwIjoxNjU0NzI2OTE1fQ.LOt_nDw3QFg-B4U5ARz4onJcEVG0qAdQbumd6ZGqzjY


###

GET http://localhost:5000/adverts



